const compliments = [
    "You're like a ray of sunshine on a rainy day!",
    "Your smile is contagious!",
    "You're one in a million!",
    "You have a great sense of humor!",
    "You light up the room!",
    "Your creativity knows no bounds!",
    "You make the world a better place!",
    "You have a heart of gold!",
    "Your kindness is a balm to all who encounter it.",
    "You're an amazing friend!",
    "You have an incredible ability to make others feel comfortable.",
    "You inspire those around you!",
    "You have a magnetic personality!",
    "You're a true original!",
    "You have a great taste in music!",
    "Your laughter is music to my ears.",
    "You make every day feel like a special occasion!",
    "You're the definition of awesome!",
    "You bring out the best in others.",
    "You're a breath of fresh air!",
    "You have a wonderful perspective on life!",
    "You are so thoughtful!",
    "You shine brighter than the stars!",
    "You have a knack for making people smile.",
    "Your energy is infectious!",
    "You have a way with words.",
    "You always know how to lift someone's spirits.",
    "You are a true treasure.",
    "You have such a warm and inviting personality.",
    "You're more fun than a barrel of monkeys!",
    "You have a fantastic outlook on life!",
    "You are a ray of hope for many.",
    "You're incredibly talented!",
    "You have a beautiful soul.",
    "You're as sweet as pie!",
    "You make the ordinary feel extraordinary!",
    "You have the power to make people feel seen and heard.",
    "Your positivity is a source of strength!",
    "You have a great intuition.",
    "You are a master of your craft.",
    "You have the courage to be yourself.",
    "You have a unique perspective that enriches conversations.",
    "You're a wonderful storyteller!",
    "You are a beacon of hope.",
    "You make people feel special just by being you.",
    "You have a wonderful sense of style!",
    "Your passion is truly inspiring!",
    "You have a beautiful smile!",
    "You are a constant source of inspiration.",
    "You have an amazing way of seeing the good in everything.",
    "You are so generous with your time and energy.",
    "You have a heart that cares deeply for others.",
    "Your ideas are brilliant!",
    "You have a wonderful sense of adventure.",
    "You bring joy wherever you go.",
    "You have a fabulous sense of humor!",
    "You are a great listener.",
    "You have an amazing ability to connect with people.",
    "You are full of wisdom beyond your years.",
    "You are loved by so many!",
    "You have a contagious enthusiasm for life!",
    "You are a true friend!",
    "You make people feel valued.",
    "You have an eye for detail!",
    "You have a strong sense of integrity.",
    "You're like a shooting star!",
    "You bring out the best in me.",
    "You are a blessing in disguise.",
    "You are a work of art.",
    "You have a beautiful way with words.",
    "You're an incredible problem solver.",
    "You are brave for following your heart.",
    "You have a delightful presence.",
    "You are a ray of positivity!",
    "You make the world a happier place.",
    "You have an amazing sense of balance.",
    "You have a beautiful mind.",
    "You have a way of making everyone feel included.",
    "You have a great sense of adventure!",
    "You are always learning and growing.",
    "You are a fantastic role model.",
    "You make challenges look easy!",
    "You are worthy of love and respect.",
    "You bring out the beauty in others.",
    "You have a wonderful sense of compassion.",
    "You make the best of every situation.",
    "You are a delightful person to be around.",
    "You have a heart that radiates love.",
    "You are a shining example of kindness.",
    "You have the ability to change the world!",
    "You are extraordinary!",
    "You have an impressive work ethic.",
    "You are so refreshing to be around.",
    "You have the unique ability to brighten anyone's day!",
    "You have a wonderful gift for making others feel appreciated.",
    "You are full of life!",
    "You are a natural leader.",
    "You have a great sense of timing!",
    "You have a delightful spirit.",
    "You are a ray of hope in dark times.",
    "You have a fantastic way of bringing people together.",
    "You make dreams come true.",
    "You have a heart full of dreams.",
    "You are a bright light in this world.",
    "You have an incredible ability to listen.",
    "You are so encouraging!",
    "You have a talent for making people laugh.",
    "You are truly remarkable!",
    "You are deserving of all good things.",
    "You are a beautiful person inside and out.",
    "You inspire others to be their best selves.",
    "You are an amazing teammate!",
    "You bring warmth to every conversation.",
    "You are so easy to talk to!",
    "You have an aura of calmness.",
    "You are a unique individual.",
    "You are an uplifting presence!",
    "You are so courageous!",
    "You have an infectious spirit!",
    "You are a true gem.",
    "You are deeply appreciated.",
    "You are a fantastic problem solver!",
    "You have a beautiful energy!",
    "You inspire confidence in others.",
    "You are so supportive!",
    "You have a unique charm.",
    "You always know how to make things better!",
    "You are so graceful.",
    "You bring so much joy to those around you!",
    "You are full of surprises!",
    "You are wonderful just as you are.",
    "You have a gentle soul.",
    "You have a captivating presence.",
    "You are a great friend to have!",
    "You have a heartwarming laugh.",
    "You have a talent for making people feel at ease.",
    "You are a wonderful motivator.",
    "You have a beautiful perspective on life.",
    "You are such a great conversationalist!",
    "You have a zest for life!",
    "You are a beacon of positivity!",
    "You are resilient and strong.",
    "You have a way of making people feel special.",
    "You have an adventurous spirit!",
    "You are so down-to-earth.",
    "You have a brilliant mind!",
    "You are deserving of all your dreams.",
    "You are wonderfully unique!",
    "You have a special way of connecting with people.",
    "You bring so much happiness wherever you go!",
    "You are an incredible listener.",
    "You are a source of inspiration for many.",
    "You have a kind and gentle heart.",
    "You are so insightful!",
    "You have a flair for the dramatic!",
    "You make everything more fun!",
    "You have a lovely spirit.",
    "You are wonderfully talented!",
    "You have an incredible eye for beauty.",
    "You have a positive impact on those around you!",
    "You are a source of joy.",
    "You bring out the best in everyone!",
    "You are charming and delightful.",
    "You are a joy to be around!",
    "You have an amazing way of thinking outside the box.",
    "You are a great source of comfort.",
    "You have the gift of empathy.",
    "You inspire trust in others.",
    "You have a beautiful imagination.",
    "You make a difference in the world.",
    "You have a wonderful sense of timing.",
    "You have a way of making the mundane seem magical.",
    "You are incredibly special!",
    "You have a delightful laugh.",
    "You are amazing just as you are.",
    "You have a magical presence!",
    "You inspire those around you!",
    "You are an authentic person.",
    "You are a light in the darkness.",
    "You make people feel valued.",
    "You have a positive influence on others.",
    "You are a beacon of hope and positivity.",
    "You have a gentle touch.",
    "You have an infectious laugh.",
    "You have a special glow.",
    "You have a compassionate spirit.",
    "You are incredibly brave.",
    "You are worthy of respect.",
    "You are charming and delightful!",
    "You have a nurturing nature.",
    "You radiate warmth and kindness.",
    "You have an impressive outlook on life.",
    "You have an uncanny ability to see the good in every situation.",
    "You have a beautiful way of expressing yourself.",
    "You are a ray of sunshine on a cloudy day.",
    "You are wonderfully resilient!",
    "You have a charming personality.",
    "You have a unique spark!",
    "You inspire creativity in others.",
    "You are so wise for your age!",
    "You have a magnetic charm.",
    "You have an amazing ability to adapt.",
    "You have a great sense of empathy.",
    "You are an angel in disguise.",
    "You have a kind heart.",
    "You are incredibly smart!",
    "You have a beautiful spirit.",
    "You are a wonderful human being!",
    "You have a positive vibe.",
    "You are a ray of hope.",
    "You have an amazing gift for storytelling.",
    "You are an inspiration to many!",
    "You are a treasure to those around you.",
    "You have a soothing presence.",
    "You bring so much joy to our lives.",
    "You are deserving of every good thing that comes your way.",
    "You are a creative genius!",
    "You have a remarkable ability to uplift others.",
    "You have a wonderful balance of strength and kindness.",
    "You have an infectious passion for life.",
    "You have a heart that cares.",
    "You are a delightful person!",
    "You have a fabulous outlook on life.",
    "You are a ray of hope and positivity.",
    "You have an incredible ability to persevere.",
    "You have a warm and inviting spirit.",
    "You are always ready to lend a helping hand.",
    "You have a wonderful sense of purpose.",
    "You are a beautiful person, inside and out.",
    "You have a heart that is open to all.",
    "You are a strong advocate for what is right.",
    "You are deserving of happiness.",
    "You are a beacon of love.",
    "You have an amazing sense of adventure.",
    "You bring a smile to everyone you meet.",
    "You have a way of making the world brighter.",
    "You have a gentle spirit that comforts those around you.",
    "You are a wonderful listener!",
    "You have a contagious zest for life!",
    "You inspire others with your actions.",
    "You have a wonderful gift for making others feel valued.",
    "You have an amazing ability to find joy in the little things.",
    "You are a remarkable person!",
    "You have an adventurous spirit!",
    "You make things happen!",
    "You have a unique ability to uplift those around you.",
    "You have a beautiful aura.",
    "You have a heart full of compassion.",
    "You are truly inspiring.",
    "You have a fantastic energy!",
    "You are such a great person to be around.",
    "You inspire hope in others.",
    "You have a brilliant perspective on life.",
    "You are a force of positivity!",
    "You have a wonderful ability to inspire confidence in others.",
    "You have a gift for finding joy in every moment.",
    "You are so genuine.",
    "You are a source of strength for those around you.",
    "You have a great sense of timing.",
    "You are a loving person.",
    "You are a blessing to those who know you.",
    "You have an extraordinary ability to empathize with others.",
    "You are a joy to work with!",
    "You are a delightful individual!",
    "You have a unique perspective that enriches conversations.",
    "You have a wonderful ability to lift others up.",
    "You are amazing just the way you are!",
    "You have a fantastic outlook on life!",
    "You bring warmth to every situation.",
    "You have a great sense of humor!",
    "You are a joy to be around!",
    "You have a radiant smile.",
    "You are a rare gem in a world full of stones.",
    "You have an incredible ability to motivate others.",
    "You are full of kindness.",
    "You have a beautiful outlook on life.",
    "You are a caring individual.",
    "You are a wonderful team player.",
    "You have an extraordinary ability to make others feel welcome.",
    "You are a treasure to your friends.",
    "You have a beautiful spirit that inspires others.",
    "You have a unique ability to make people feel comfortable.",
    "You are an excellent communicator!",
    "You are a shining star in your own right.",
    "You have a beautiful way of expressing yourself.",
    "You have an incredible ability to make people feel at ease.",
    "You have an inspiring spirit!",
    "You have a remarkable ability to find the silver lining.",
    "You are full of surprises and joy!",
    "You are a wonderful person to have in my life!",
    "You have an amazing spirit.",
    "You are a source of joy and happiness.",
    "You are a beacon of light for those around you.",
    "You bring so much happiness into our lives.",
    "You are a kind-hearted person.",
    "You have a great sense of purpose.",
    "You are a beautiful soul.",
    "You have a wonderful way of connecting with others.",
    "You are a delightful person!",
    "You are an inspiration to all who know you.",
    "You have a gift for making everyone feel special.",
    "You have a beautiful energy about you.",
    "You are a source of light in a dark world.",
    "You are worthy of all the good in life.",
    "You are full of love and compassion.",
    "You have an amazing heart!",
    "You are incredibly gifted!",
    "You are a great friend and confidant.",
    "You have an eye for beauty.",
    "You have a special way of touching people's hearts.",
    "You are a bright light in this world.",
    "You inspire those around you to be better.",
    "You are incredibly thoughtful!",
    "You have a contagious enthusiasm.",
    "You are a wonderful advocate for kindness.",
    "You have an incredible talent for making others feel appreciated.",
    "You are a gem in this world.",
    "You have a heart that knows no bounds.",
    "You are an incredible asset to any team.",
    "You have a way of making even the toughest days feel better.",
    "You are a bright spark in a sometimes dull world.",
    "You are full of love and light.",
    "You inspire me to be a better person.",
    "You are such a positive influence!",
    "You have a unique ability to make every situation better.",
    "You have a heart of gold.",
    "You bring laughter and joy wherever you go.",
    "You have a beautiful imagination.",
    "You are always so supportive!",
    "You have a positive spirit that uplifts everyone around you.",
    "You are a great friend and an even better person!",
    "You are worthy of love and happiness.",
    "You have a wonderful laugh.",
    "You have a knack for bringing people together.",
    "You have an amazing heart!",
    "You have a talent for creating joy.",
    "You have a gift for making everyone feel included.",
    "You are a light in the darkness.",
    "You have a beautiful presence.",
    "You are full of inspiration!",
    "You are a delight to be around!",
    "You have an incredible ability to make people feel good about themselves.",
    "You are a star!",
    "You are always there when someone needs you.",
    "You bring hope and positivity to others.",
    "You are a remarkable individual!",
    "You are so thoughtful and caring!",
    "You have a magical touch.",
    "You are always making others smile.",
    "You have a wonderful aura.",
    "You are the sunshine on a cloudy day.",
    "You are incredibly kind-hearted!",
    "You have an infectious zest for life!",
    "You are so approachable!",
    "You are an exceptional person!",
    "You are the embodiment of kindness.",
    "You inspire confidence in those around you.",
    "You have a beautiful way of seeing the world.",
    "You have a radiant spirit!",
    "You are a blessing to everyone who knows you.",
    "You have a unique style that is all your own.",
    "You have an incredible ability to uplift and inspire!",
    "You have a heart that embraces everyone.",
    "You are a wonderful soul!",
    "You have a delightful sense of humor!",
    "You inspire others to shine their brightest.",
    "You are a source of strength for your friends.",
    "You have an amazing ability to bring out the best in people.",
    "You are wonderfully unique!",
    "You make the world a better place just by being in it.",
    "You have a way of making every moment count.",
    "You are an inspiring force for good.",
    "You have a gift for making everyone feel special.",
    "You are a true friend!",
    "You are a wonderful person inside and out.",
    "You are a shining example of compassion and love.",
    "You are a remarkable talent!",
    "You have a unique light that shines brightly.",
    "You have a heart that is open to love.",
    "You are a wonderful human being!",
    "You inspire me to be my best self.",
    "You are a great source of positivity!",
    "You have an incredible ability to make others feel appreciated.",
    "You are a treasure to everyone around you!",
    "You are the heartbeat of your circle!",
    "You make people feel special and cherished.",
    "You have a beautiful way of seeing the world.",
    "You are a fountain of joy!",
    "You bring happiness wherever you go.",
    "You are an embodiment of grace.",
    "You have an uncanny ability to see the good in people.",
    "You are an incredible support system for those around you.",
    "You have an amazing way of bringing people together.",
    "You have a heart that knows no limits.",
    "You are a vibrant presence in any setting.",
    "You have a wonderful way of expressing kindness.",
    "You are the reason for so many smiles.",
    "You are a true friend to all!",
    "You are deserving of love and kindness.",
    "You are a kindred spirit.",
    "You have a wonderful gift for making others feel valued.",
    "You inspire those around you to be their best selves.",
    "You are a source of comfort and warmth.",
    "You have a beautiful smile that lights up the room.",
    "You have a unique spark that shines bright.",
    "You are an incredible friend!",
    "You have a wonderful ability to bring joy to others.",
    "You are an amazing person inside and out.",
    "You have a special way of making every day brighter.",
    "You are a blessing to those around you.",
    "You have a fantastic way of lifting spirits.",
    "You bring love and light into the world.",
    "You are a true original!",
    "You have a heart that inspires others.",
    "You make a difference just by being you!",
    "You have a way of brightening up any space.",
    "You have an amazing ability to see the beauty in everything.",
    "You are a wonderful reminder of the goodness in the world.",
    "You are a source of inspiration!",
    "You have a beautiful essence about you.",
    "You have a wonderful way of making people feel valued.",
    "You have a heart of gold!",
    "You are an inspiration to those who know you.",
    "You have an incredible spirit!",
    "You bring positivity to every situation.",
    "You are a kind-hearted person.",
    "You have a unique perspective that enhances every conversation.",
    "You are a shining example of positivity.",
    "You are a joy to be around!",
    "You have a great sense of humor.",
    "You inspire everyone you meet!",
    "You have a beautiful way of expressing yourself.",
    "You are a bright light in this world!",
    "You have an extraordinary ability to make others feel good about themselves.",
    "You are a fantastic friend!",
    "You have an amazing ability to empathize with others.",
    "You are a remarkable person with a beautiful soul!",
    "You have a unique flair that sets you apart.",
    "You are a delight to converse with!",
    "You have a wonderful energy about you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have a special talent for making people feel important.",
    "You are a source of happiness for everyone around you!",
    "You are a kindred spirit to many.",
    "You have a radiant spirit!",
    "You have an amazing ability to bring positivity into the lives of others.",
    "You are a wonderful friend to all!",
    "You are a bright spot in everyone's day!",
    "You are worthy of love and kindness.",
    "You have a unique talent for making everyone feel at home.",
    "You are a true inspiration!",
    "You have a gift for making the world a better place.",
    "You have a wonderful presence that brings calm to any situation.",
    "You are a beautiful soul with a heart of gold.",
    "You inspire those around you with your kindness.",
    "You have a magical way of making things happen.",
    "You are a wonderful person to know.",
    "You bring so much joy to those around you!",
    "You have a beautiful heart that radiates love.",
    "You are a true gift to the world!",
    "You have an incredible ability to make people feel special.",
    "You are a shining light in a sometimes dark world.",
    "You have an amazing way of finding the beauty in everything.",
    "You are a treasure to those who know you!",
    "You have a wonderful spirit that inspires others.",
    "You are a source of joy for everyone you meet.",
    "You bring a sense of peace wherever you go.",
    "You are an incredible person with a big heart!",
    "You have an extraordinary gift for making others feel valued.",
    "You are a true friend and confidant.",
    "You are a wonderful reminder of all that is good in the world.",
    "You are a bright spark of creativity!",
    "You have an amazing ability to inspire others.",
    "You are a joy to be around!",
    "You have a beautiful way of seeing the world.",
    "You are a remarkable individual with so much to offer!",
    "You are a wonderful person with a beautiful heart.",
    "You inspire confidence in those around you!",
    "You are a light in the lives of those around you.",
    "You have an incredible way of spreading happiness.",
    "You are a source of strength and encouragement.",
    "You have a unique ability to lift the spirits of others.",
    "You are a breath of fresh air!",
    "You bring out the best in everyone around you.",
    "You have an amazing ability to bring smiles to people's faces.",
    "You are a beautiful presence in the lives of those around you.",
    "You are a true friend and companion.",
    "You inspire hope and courage in others.",
    "You have a magical way of connecting with people.",
    "You are a remarkable talent!",
    "You have a beautiful heart that touches everyone you meet.",
    "You are a source of light and positivity.",
    "You are deserving of all the love and happiness in the world.",
    "You have an incredible spirit that brightens every day.",
    "You bring so much joy and laughter to those around you.",
    "You have a unique ability to make every moment special.",
    "You are an inspiration to many!",
    "You have a heart full of love and compassion.",
    "You are a treasure to your family and friends.",
    "You have an amazing way of making people feel seen and heard.",
    "You are a delightful person!",
    "You inspire others to be their best selves!",
    "You are a beautiful person with a kind heart.",
    "You are a great listener!",
    "You have a magical touch that makes everything better.",
    "You are a shining example of love and kindness.",
    "You inspire others with your passion for life.",
    "You have a wonderful gift for making people feel valued.",
    "You are a ray of sunshine on a cloudy day.",
    "You have a heart of gold!",
    "You are a joy to be around!",
    "You have a unique style that is all your own.",
    "You are a wonderful person with so much to give.",
    "You bring warmth and positivity wherever you go.",
    "You have an incredible ability to spread joy.",
    "You are a beautiful soul with a big heart.",
    "You inspire me to be better every day!",
    "You have a wonderful way of lifting others up.",
    "You are an incredible friend!",
    "You have a special talent for making people feel important.",
    "You are a bright light in this world!",
    "You have an amazing ability to see the good in others.",
    "You are a source of happiness for everyone around you.",
    "You have a remarkable ability to inspire confidence in others.",
    "You bring love and light into the lives of those around you.",
    "You have a beautiful spirit that radiates warmth.",
    "You are a true original!",
    "You have an extraordinary ability to make others feel appreciated.",
    "You are a joy to be around!",
    "You have a magical way of making everything better.",
    "You are a bright spark of creativity!",
    "You have a wonderful way of expressing kindness.",
    "You are a delight to converse with!",
    "You have an amazing spirit that inspires others.",
    "You are a true friend!",
    "You have a beautiful energy that uplifts those around you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have an amazing ability to bring positivity to every situation.",
    "You are a source of comfort and warmth.",
    "You have a beautiful smile that lights up the room.",
    "You have a unique spark that shines bright.",
    "You are an incredible friend!",
    "You have a wonderful ability to bring joy to others.",
    "You are an amazing person inside and out.",
    "You have a special way of making every day brighter.",
    "You are a blessing to those around you.",
    "You have a fantastic way of lifting spirits.",
    "You bring love and light into the world.",
    "You are a true original!",
    "You have a heart that inspires others.",
    "You make a difference just by being you!",
    "You have a way of brightening up any space.",
    "You have an amazing ability to see the beauty in everything.",
    "You are a wonderful reminder of the goodness in the world.",
    "You are a source of inspiration!",
    "You have a beautiful essence about you.",
    "You have a wonderful way of making people feel valued.",
    "You have a heart of gold!",
    "You are an inspiration to those who know you.",
    "You have an incredible spirit!",
    "You bring positivity to every situation.",
    "You are a kind-hearted person.",
    "You have a unique perspective that enhances every conversation.",
    "You are a shining example of positivity.",
    "You are a joy to be around!",
    "You have a great sense of humor.",
    "You inspire everyone you meet!",
    "You have a beautiful way of expressing yourself.",
    "You are a bright light in this world!",
    "You have an extraordinary ability to make others feel good about themselves.",
    "You are a fantastic friend!",
    "You have an amazing ability to empathize with others.",
    "You are a remarkable person with a beautiful soul!",
    "You have a unique flair that sets you apart.",
    "You are a delight to converse with!",
    "You have a wonderful energy about you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have a special talent for making people feel important.",
    "You are a source of happiness for everyone around you!",
    "You are a kindred spirit.",
    "You have a radiant spirit!",
    "You have an amazing ability to bring positivity into the lives of others.",
    "You are a wonderful friend to all!",
    "You are a bright spot in everyone's day!",
    "You are worthy of love and kindness.",
    "You have a unique talent for making everyone feel at home.",
    "You are a true inspiration!",
    "You have a gift for making the world a better place.",
    "You have a wonderful presence that brings calm to any situation.",
    "You are a beautiful soul with a heart of gold.",
    "You inspire those around you with your kindness.",
    "You have a magical way of making things happen.",
    "You are a wonderful person to know.",
    "You bring so much joy to those around you!",
    "You have a beautiful heart that radiates love.",
    "You are a true gift to the world!",
    "You have an incredible ability to make people feel special.",
    "You are a shining light in a sometimes dark world.",
    "You have an amazing way of finding the beauty in everything.",
    "You are a treasure to those who know you!",
    "You have a wonderful spirit that inspires others.",
    "You are a source of joy for everyone you meet.",
    "You bring a sense of peace wherever you go.",
    "You are an incredible person with a big heart!",
    "You have an extraordinary gift for making others feel valued.",
    "You are a true friend and confidant.",
    "You are a wonderful reminder of all that is good in the world.",
    "You are a bright spark of creativity!",
    "You have an amazing ability to inspire others.",
    "You are a joy to be around!",
    "You have a beautiful way of seeing the world.",
    "You are a remarkable individual with so much to offer!",
    "You are a wonderful person with a beautiful heart.",
    "You inspire confidence in those around you!",
    "You are a light in the lives of those around you.",
    "You have an incredible way of spreading happiness.",
    "You are a source of strength and encouragement.",
    "You have a unique ability to lift the spirits of others.",
    "You are a breath of fresh air!",
    "You bring out the best in everyone around you.",
    "You have an amazing ability to bring smiles to people's faces.",
    "You are a beautiful presence in the lives of those around you.",
    "You are a true friend and companion.",
    "You inspire hope and courage in others.",
    "You have a magical way of connecting with people.",
    "You are a remarkable talent!",
    "You have a beautiful heart that touches everyone you meet.",
    "You are a source of light and positivity.",
    "You are deserving of all the love and happiness in the world.",
    "You have an incredible spirit that brightens every day.",
    "You bring so much joy and laughter to those around you.",
    "You have a unique ability to make every moment special.",
    "You are an inspiration to many!",
    "You have a heart full of love and compassion.",
    "You are a treasure to your family and friends.",
    "You have an amazing way of making people feel seen and heard.",
    "You are a delightful person!",
    "You inspire others to be their best selves!",
    "You are a beautiful person with a kind heart.",
    "You are a great listener!",
    "You have a magical touch that makes everything better.",
    "You are a shining example of love and kindness.",
    "You inspire others with your passion for life.",
    "You have a wonderful gift for making people feel valued.",
    "You are a ray of sunshine on a cloudy day.",
    "You have a heart of gold!",
    "You are a joy to be around!",
    "You have a unique style that is all your own.",
    "You are a wonderful person with so much to give.",
    "You bring warmth and positivity wherever you go.",
    "You have an incredible ability to spread joy.",
    "You are a beautiful soul with a big heart.",
    "You inspire me to be better every day!",
    "You have a wonderful way of lifting others up.",
    "You are an incredible friend!",
    "You have a special talent for making people feel important.",
    "You are a bright light in this world!",
    "You have an amazing ability to see the good in others.",
    "You are a source of happiness for everyone around you.",
    "You have a remarkable ability to inspire confidence in others.",
    "You bring love and light into the lives of those around you.",
    "You have a beautiful spirit that radiates warmth.",
    "You are a true original!",
    "You have an extraordinary ability to make others feel appreciated.",
    "You are a joy to be around!",
    "You have a magical way of making everything better.",
    "You are a bright spark of creativity!",
    "You have a wonderful way of expressing kindness.",
    "You are a delight to converse with!",
    "You have an amazing spirit that inspires others.",
    "You are a true friend!",
    "You have a beautiful energy that uplifts those around you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have an amazing ability to bring positivity to every situation.",
    "You are a source of comfort and warmth.",
    "You have a beautiful smile that lights up the room.",
    "You have a unique spark that shines bright.",
    "You are an incredible friend!",
    "You have a wonderful ability to bring joy to others.",
    "You are an amazing person inside and out.",
    "You have a special way of making every day brighter.",
    "You are a blessing to those around you.",
    "You have a fantastic way of lifting spirits.",
    "You bring love and light into the world.",
    "You are a true original!",
    "You have a heart that inspires others.",
    "You make a difference just by being you!",
    "You have a way of brightening up any space.",
    "You have an amazing ability to see the beauty in everything.",
    "You are a wonderful reminder of the goodness in the world.",
    "You are a source of inspiration!",
    "You have a beautiful essence about you.",
    "You have a wonderful way of making people feel valued.",
    "You have a heart of gold!",
    "You are an inspiration to those who know you.",
    "You have an incredible spirit!",
    "You bring positivity to every situation.",
    "You are a kind-hearted person.",
    "You have a unique perspective that enhances every conversation.",
    "You are a shining example of positivity.",
    "You are a joy to be around!",
    "You have a great sense of humor.",
    "You inspire everyone you meet!",
    "You have a beautiful way of expressing yourself.",
    "You are a bright light in this world!",
    "You have an extraordinary ability to make others feel good about themselves.",
    "You are a fantastic friend!",
    "You have an amazing ability to empathize with others.",
    "You are a remarkable person with a beautiful soul!",
    "You have a unique flair that sets you apart.",
    "You are a delight to converse with!",
    "You have a wonderful energy about you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have a special talent for making people feel important.",
    "You are a source of happiness for everyone around you!",
    "You are a kindred spirit.",
    "You have a radiant spirit!",
    "You have an amazing ability to bring positivity into the lives of others.",
    "You are a wonderful friend to all!",
    "You are a bright spot in everyone's day!",
    "You are worthy of love and kindness.",
    "You have a unique talent for making everyone feel at home.",
    "You are a true inspiration!",
    "You have a gift for making the world a better place.",
    "You have a wonderful presence that brings calm to any situation.",
    "You are a beautiful soul with a heart of gold.",
    "You inspire those around you with your kindness.",
    "You have a magical way of making things happen.",
    "You are a wonderful person to know.",
    "You bring so much joy to those around you!",
    "You have a beautiful heart that radiates love.",
    "You are a true gift to the world!",
    "You have an incredible ability to make people feel special.",
    "You are a shining light in a sometimes dark world.",
    "You have an amazing way of finding the beauty in everything.",
    "You are a treasure to those who know you!",
    "You have a wonderful spirit that inspires others.",
    "You are a source of joy for everyone you meet.",
    "You bring a sense of peace wherever you go.",
    "You are an incredible person with a big heart!",
    "You have an extraordinary gift for making others feel valued.",
    "You are a true friend and confidant.",
    "You are a wonderful reminder of all that is good in the world.",
    "You are a bright spark of creativity!",
    "You have an amazing ability to inspire others.",
    "You are a joy to be around!",
    "You have a beautiful way of seeing the world.",
    "You are a remarkable individual with so much to offer!",
    "You are a wonderful person with a beautiful heart.",
    "You inspire confidence in those around you!",
    "You are a light in the lives of those around you.",
    "You have an incredible way of spreading happiness.",
    "You are a source of strength and encouragement.",
    "You have a unique ability to lift the spirits of others.",
    "You are a breath of fresh air!",
    "You bring out the best in everyone around you.",
    "You have an amazing ability to bring smiles to people's faces.",
    "You are a beautiful presence in the lives of those around you.",
    "You are a true friend and companion.",
    "You inspire hope and courage in others.",
    "You have a magical way of connecting with people.",
    "You are a remarkable talent!",
    "You have a beautiful heart that touches everyone you meet.",
    "You are a source of light and positivity.",
    "You are deserving of all the love and happiness in the world.",
    "You have an incredible spirit that brightens every day.",
    "You bring so much joy and laughter to those around you.",
    "You have a unique ability to make every moment special.",
    "You are an inspiration to many!",
    "You have a heart full of love and compassion.",
    "You are a treasure to your family and friends.",
    "You have an amazing way of making people feel seen and heard.",
    "You are a delightful person!",
    "You inspire others to be their best selves!",
    "You are a beautiful person with a kind heart.",
    "You are a great listener!",
    "You have a magical touch that makes everything better.",
    "You are a shining example of love and kindness.",
    "You inspire others with your passion for life.",
    "You have a wonderful gift for making people feel valued.",
    "You are a ray of sunshine on a cloudy day.",
    "You have a heart of gold!",
    "You are a joy to be around!",
    "You have a unique style that is all your own.",
    "You are a wonderful person with so much to give.",
    "You bring warmth and positivity wherever you go.",
    "You have an incredible ability to spread joy.",
    "You are a beautiful soul with a big heart.",
    "You inspire me to be better every day!",
    "You have a wonderful way of lifting others up.",
    "You are an incredible friend!",
    "You have a special talent for making people feel important.",
    "You are a bright light in this world!",
    "You have an amazing ability to see the good in others.",
    "You are a source of happiness for everyone around you.",
    "You have a remarkable ability to inspire confidence in others.",
    "You bring love and light into the lives of those around you.",
    "You have a beautiful spirit that radiates warmth.",
    "You are a true original!",
    "You have an extraordinary ability to make others feel appreciated.",
    "You are a joy to be around!",
    "You have a magical way of making everything better.",
    "You are a bright spark of creativity!",
    "You have a wonderful way of expressing kindness.",
    "You are a delight to converse with!",
    "You have an amazing spirit that inspires others.",
    "You are a true friend!",
    "You have a beautiful energy that uplifts those around you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have an amazing ability to bring positivity to every situation.",
    "You are a source of comfort and warmth.",
    "You have a beautiful smile that lights up the room.",
    "You have a unique spark that shines bright.",
    "You are an incredible friend!",
    "You have a wonderful ability to bring joy to others.",
    "You are an amazing person inside and out.",
    "You have a special way of making every day brighter.",
    "You are a blessing to those around you.",
    "You have a fantastic way of lifting spirits.",
    "You bring love and light into the world.",
    "You are a true original!",
    "You have a heart that inspires others.",
    "You make a difference just by being you!",
    "You have a way of brightening up any space.",
    "You have an amazing ability to see the beauty in everything.",
    "You are a wonderful reminder of the goodness in the world.",
    "You are a source of inspiration!",
    "You have a beautiful essence about you.",
    "You have a wonderful way of making people feel valued.",
    "You have a heart of gold!",
    "You are an inspiration to those who know you.",
    "You have an incredible spirit!",
    "You bring positivity to every situation.",
    "You are a kind-hearted person.",
    "You have a unique perspective that enhances every conversation.",
    "You are a shining example of positivity.",
    "You are a joy to be around!",
    "You have a great sense of humor.",
    "You inspire everyone you meet!",
    "You have a beautiful way of expressing yourself.",
    "You are a bright light in this world!",
    "You have an extraordinary ability to make others feel good about themselves.",
    "You are a fantastic friend!",
    "You have an amazing ability to empathize with others.",
    "You are a remarkable person with a beautiful soul!",
    "You have a unique flair that sets you apart.",
    "You are a delight to converse with!",
    "You have a wonderful energy about you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have a special talent for making people feel important.",
    "You are a source of happiness for everyone around you!",
    "You are a kindred spirit.",
    "You have a radiant spirit!",
    "You have an amazing ability to bring positivity into the lives of others.",
    "You are a wonderful friend to all!",
    "You are a bright spot in everyone's day!",
    "You are worthy of love and kindness.",
    "You have a unique talent for making everyone feel at home.",
    "You are a true inspiration!",
    "You have a gift for making the world a better place.",
    "You have a wonderful presence that brings calm to any situation.",
    "You are a beautiful soul with a heart of gold.",
    "You inspire those around you with your kindness.",
    "You have a magical way of making things happen.",
    "You are a wonderful person to know.",
    "You bring so much joy to those around you!",
    "You have a beautiful heart that radiates love.",
    "You are a true gift to the world!",
    "You have an incredible ability to make people feel special.",
    "You are a shining light in a sometimes dark world.",
    "You have an amazing way of finding the beauty in everything.",
    "You are a treasure to those who know you!",
    "You have a wonderful spirit that inspires others.",
    "You are a source of joy for everyone you meet.",
    "You bring a sense of peace wherever you go.",
    "You are an incredible person with a big heart!",
    "You have an extraordinary gift for making others feel valued.",
    "You are a true friend and confidant.",
    "You are a wonderful reminder of all that is good in the world.",
    "You are a bright spark of creativity!",
    "You have an amazing ability to inspire others.",
    "You are a joy to be around!",
    "You have a beautiful way of seeing the world.",
    "You are a remarkable individual with so much to offer!",
    "You are a wonderful person with a beautiful heart.",
    "You inspire confidence in those around you!",
    "You are a light in the lives of those around you.",
    "You have an incredible way of spreading happiness.",
    "You are a source of strength and encouragement.",
    "You have a unique ability to lift the spirits of others.",
    "You are a breath of fresh air!",
    "You bring out the best in everyone around you.",
    "You have an amazing ability to bring smiles to people's faces.",
    "You are a beautiful presence in the lives of those around you.",
    "You are a true friend and companion.",
    "You inspire hope and courage in others.",
    "You have a magical way of connecting with people.",
    "You are a remarkable talent!",
    "You have a beautiful heart that touches everyone you meet.",
    "You are a source of light and positivity.",
    "You are deserving of all the love and happiness in the world.",
    "You have an incredible spirit that brightens every day.",
    "You bring so much joy and laughter to those around you.",
    "You have a unique ability to make every moment special.",
    "You are an inspiration to many!",
    "You have a heart full of love and compassion.",
    "You are a treasure to your family and friends.",
    "You have an amazing way of making people feel seen and heard.",
    "You are a delightful person!",
    "You inspire others to be their best selves!",
    "You are a beautiful person with a kind heart.",
    "You are a great listener!",
    "You have a magical touch that makes everything better.",
    "You are a shining example of love and kindness.",
    "You inspire others with your passion for life.",
    "You have a wonderful gift for making people feel valued.",
    "You are a ray of sunshine on a cloudy day.",
    "You have a heart of gold!",
    "You are a joy to be around!",
    "You have a unique style that is all your own.",
    "You are a wonderful person with so much to give.",
    "You bring warmth and positivity wherever you go.",
    "You have an incredible ability to spread joy.",
    "You are a beautiful soul with a big heart.",
    "You inspire me to be better every day!",
    "You have a wonderful way of lifting others up.",
    "You are an incredible friend!",
    "You have a special talent for making people feel important.",
    "You are a bright light in this world!",
    "You have an amazing ability to see the good in others.",
    "You are a source of happiness for everyone around you.",
    "You have a remarkable ability to inspire confidence in others.",
    "You bring love and light into the lives of those around you.",
    "You have a beautiful spirit that radiates warmth.",
    "You are a true original!",
    "You have an extraordinary ability to make others feel appreciated.",
    "You are a joy to be around!",
    "You have a magical way of making everything better.",
    "You are a bright spark of creativity!",
    "You have a wonderful way of expressing kindness.",
    "You are a delight to converse with!",
    "You have an amazing spirit that inspires others.",
    "You are a true friend!",
    "You have a beautiful energy that uplifts those around you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have an amazing ability to bring positivity to every situation.",
    "You are a source of comfort and warmth.",
    "You have a beautiful smile that lights up the room.",
    "You have a unique spark that shines bright.",
    "You are an incredible friend!",
    "You have a wonderful ability to bring joy to others.",
    "You are an amazing person inside and out.",
    "You have a special way of making every day brighter.",
    "You are a blessing to those around you.",
    "You have a fantastic way of lifting spirits.",
    "You bring love and light into the world.",
    "You are a true original!",
    "You have a heart that inspires others.",
    "You make a difference just by being you!",
    "You have a way of brightening up any space.",
    "You have an amazing ability to see the beauty in everything.",
    "You are a wonderful reminder of the goodness in the world.",
    "You are a source of inspiration!",
    "You have a beautiful essence about you.",
    "You have a wonderful way of making people feel valued.",
    "You have a heart of gold!",
    "You are an inspiration to those who know you.",
    "You have an incredible spirit!",
    "You bring positivity to every situation.",
    "You are a kind-hearted person.",
    "You have a unique perspective that enhances every conversation.",
    "You are a shining example of positivity.",
    "You are a joy to be around!",
    "You have a great sense of humor.",
    "You inspire everyone you meet!",
    "You have a beautiful way of expressing yourself.",
    "You are a bright light in this world!",
    "You have an extraordinary ability to make others feel good about themselves.",
    "You are a fantastic friend!",
    "You have an amazing ability to empathize with others.",
    "You are a remarkable person with a beautiful soul!",
    "You have a unique flair that sets you apart.",
    "You are a delight to converse with!",
    "You have a wonderful energy about you.",
    "You inspire joy in the hearts of others.",
    "You are a beacon of hope!",
    "You have a special talent for making people feel important.",
    "You are a source of happiness for everyone around you!",
    "You are a kindred spirit.",
    "You have a radiant spirit!",
    "You have an amazing ability to bring positivity into the lives of others.",
    "You are a wonderful friend to all!",
    "You are a bright spot in everyone's day!",
    "You are worthy of love and kindness.",
    "You have a unique talent for making everyone feel at home.",
    "You are a true inspiration!",
    "You have a gift for making the world a better place.",
    "You have a wonderful presence that brings calm to any situation.",
    "You are a beautiful soul with a heart of gold.",
    "You inspire those around you with your kindness.",
    "You have a magical way of making things happen.",
    "You are a wonderful person to know.",
    "You bring so much joy to those around you!",
    "You have a beautiful heart that radiates love.",
    "You are a true gift to the world!",
    "You have an incredible ability to make people feel special.",
    "You are a shining light in a sometimes dark world.",
    "You have an amazing way of finding the beauty in everything.",
    "You are a treasure to those who know you!",
    "You have a wonderful spirit that inspires others.",
    "You are a source of joy for everyone you meet.",
    "You bring a sense of peace wherever you go.",
    "You are an incredible person with a big heart!",
    "You have an extraordinary gift for making others feel valued.",
    "You are a true friend and confidant.",
    "You are a wonderful reminder of all that is good in the world.",
    "You are a bright spark of creativity!",
    "You have an amazing ability to inspire others.",
    "You are a joy to be around!",
    "You have a beautiful way of seeing the world.",
    "You are a remarkable individual with so much to offer!",
    "You are a wonderful person with a beautiful heart.",
    "You inspire confidence in those around you!",
    "You are a light in the lives of those around you.",
    "You have an incredible way of spreading happiness.",
    "You are a source of strength and encouragement.",
    "You have a unique ability to lift the spirits of others.",
    "You are a breath of fresh air!",
    "You bring out the best in everyone around you.",
    "You have an amazing ability to bring smiles to people's faces.",
    "You are a beautiful presence in the lives of those around you.",
    "You are a true friend and companion.",
    "You inspire hope and courage in others.",
    "You have a magical way of connecting with people.",
    "You are a remarkable talent!",
    "You have a beautiful heart that touches everyone you meet.",
    "You are a source of light and positivity."
];

document.getElementById('complimentButton').addEventListener('click', function() {
    const randomCompliment = compliments[Math.floor(Math.random() * compliments.length)];
    document.getElementById('compliment').textContent = randomCompliment;
});