const news = [
    "Local cat elected mayor!",
    "Scientists discover that pizza is a vegetable.",
    "New study finds that playing video games increases intelligence.",
    "Area man claims he can talk to plants.",
    "Aliens spotted at local coffee shop!",
    "Dog becomes internet sensation after saving owner from fire.",
    "City introduces new public transport system powered by hamsters.",
    "Scientists successfully teach goldfish to play fetch.",
    "Local bakery offers free donuts to anyone who can beat the owner in chess.",
    "Residents report mysterious lights in the sky; UFO enthusiasts gather.",
    "World's oldest tree found to be 5,000 years old.",
    "New app promises to translate your dog’s barks into English.",
    "Local library hosts 'Read a Book to a Goat' event.",
    "Incredible turn of events: local squirrel wins marathon.",
    "Frog becomes internet celebrity after hopping into a Zoom call.",
    "New study reveals cats secretly rule the internet.",
    "Area woman opens business selling personalized cloud shapes.",
    "Town holds annual 'World's Largest Potato' contest.",
    "Researchers develop chocolate that can cure hiccups.",
    "Man claims to have invented self-slicing bread.",
    "New fitness trend: underwater knitting classes.",
    "Local artist creates sculptures from recycled pizza boxes.",
    "Government discovers an ancient civilization in a suburban backyard.",
    "Woman breaks world record for most socks worn at once.",
    "Bizarre plant species discovered that grows hair instead of leaves.",
    "City council votes to rename street after beloved local dog.",
    "Scientists confirm that laughter really is the best medicine.",
    "Local child solves Rubik's cube blindfolded at age 5.",
    "World record set for longest chicken dance.",
    "Newly discovered ocean species resembles a dancing jellybean.",
    "Local farmer's tomatoes win 'Best in Show' at state fair.",
    "Dog trainer teaches pets how to do taxes.",
    "World’s first 3D-printed house opens for public tours.",
    "Residents unite to save endangered species of sock puppet.",
    "Cat café opens, serving only organic catnip lattes.",
    "New study shows that eating dessert first leads to a happier life.",
    "Local man claims he can taste the color of music.",
    "Scientists create ice cream that never melts.",
    "Mysterious creature spotted in local park; locals divided.",
    "Area high school hosts annual 'Pajama Day' with rave reviews.",
    "Local chef makes headlines with spicy chocolate sauce.",
    "Town holds first-ever 'Invisible Dog Parade'.",
    "New discovery: squirrels have a secret language.",
    "Unbelievable: goldfish wins talent show with magic trick.",
    "Local children create fairy garden to attract real fairies.",
    "Studies show that plants can grow better with classical music.",
    "Man dresses as a superhero to deliver pizzas around town.",
    "Local couple holds wedding ceremony in a giant inflatable dinosaur.",
    "New study finds that watching cute animal videos boosts productivity.",
    "Area school introduces mandatory 'Goat Therapy' sessions.",
    "Mysterious stone circle discovered in local farmer's field.",
    "Local artist paints murals on city sidewalks to brighten the community.",
    "Incredible discovery: mushrooms that glow in the dark.",
    "Woman becomes local hero after rescuing turtle from a busy road.",
    "Local coffee shop offers discounts for customers with pet goldfish.",
    "New trend: hosting 'silent disco' parties in library.",
    "World's largest collection of rubber ducks found in attic.",
    "Scientists create robot that can fold laundry.",
    "Local athlete breaks record for most pancakes eaten in one sitting.",
    "Festival held in honor of local legend: the 'Dancing Frog'.",
    "Community garden yields record number of giant zucchinis.",
    "Area man claims he can communicate with extraterrestrial beings.",
    "Local author writes best-selling book about the secret lives of cats.",
    "School introduces 'Frog Jumping' as a new competitive sport.",
    "Residents start petition to make Friday a national holiday.",
    "New scientific study shows that naps improve memory retention.",
    "Town hosts annual 'Dress Like Your Pet Day'.",
    "Incredible art installation made entirely of bubble wrap.",
    "Local farm produces world's largest watermelon.",
    "Aliens deliver message: 'We come in peace and love pizza'.",
    "Dog named Mayor wins re-election by a landslide.",
    "Bizarre fish species discovered that glows when happy.",
    "Community comes together for 'Day of Kindness' event.",
    "New yoga class for goats gains popularity.",
    "Local hero saves stranded kitten from a tree.",
    "Scientists create edible water bottles to reduce plastic waste.",
    "Annual 'Chocolate Festival' attracts visitors from across the country.",
    "Area woman breaks world record for fastest time to eat a burrito.",
    "New trend: using llamas as therapy animals.",
    "Local library introduces 'Pajama Storytime' for kids.",
    "Festival celebrates the art of cheese sculpting.",
    "Area band becomes famous for playing only songs about fruit.",
    "Man claims to have invented a time machine made of cardboard.",
    "World's first cat café with a rooftop garden opens.",
    "Local family adopts a pig as a pet; chaos ensues.",
    "Incredible discovery: butterflies that taste with their feet.",
    "Scientists unveil robot that can paint like Van Gogh.",
    "Area woman bakes world's largest cookie in her backyard.",
    "Festival dedicated to all things banana attracts huge crowds.",
    "New study finds that being silly can enhance creativity.",
    "Local artist creates sculptures that come to life.",
    "City introduces 'Parkour for Seniors' classes.",
    "Unbelievable: man grows a beard made of vegetables.",
    "Town holds 'World's Largest Bubble Wrap Pop' event.",
    "Residents unite to create a community mural.",
    "Incredible invention: self-cleaning dog house.",
    "New competition: 'Extreme Gardening' showcases unique plants.",
    "Local high school hosts annual 'Chalk Art Festival'.",
    "Scientists confirm that hugging trees reduces stress.",
    "Local cat becomes the subject of a viral documentary.",
    "New app helps users find the best places to nap.",
    "Town installs giant rubber duck in fountain as a tourist attraction.",
    "Area women hold 'Wiggle Dance Party' for charity.",
    "Incredible breakthrough: scientists find way to reverse aging in fruit flies.",
    "Festival celebrates the joy of pancakes with a flip-a-thon.",
    "Local theater company presents 'Cats: The Musical' starring real cats.",
    "Community garden project encourages neighbors to grow food together.",
    "World record set for most balloons released at once.",
    "Area man claims he has found the fountain of youth in his backyard.",
    "Local kids host lemonade stand to raise money for a new playground.",
    "Scientists discover a new species of dancing ant.",
    "City council approves plans for a 'Hug-a-Thon' event.",
    "Local coffee shop introduces 'Coffee for Cats' event.",
    "Incredible story: dog saves owner from a bear attack.",
    "Festival features a 'World's Largest Ice Cream Sundae' competition.",
    "New sport: competitive rock skipping takes off.",
    "Local artist creates living art installations using plants.",
    "New evidence suggests that dinosaurs may have had feathers.",
    "City unveils plans for a 'World's Largest Jigsaw Puzzle'.",
    "Local librarian starts 'Read to a Dog' program.",
    "Incredible invention: solar-powered ice cream truck.",
    "Residents hold annual 'Silly Hat Parade'.",
    "Local man discovers a new species of frog in his backyard.",
    "Community comes together to build a treehouse for kids.",
    "Festival celebrates the beauty of clouds with a 'Cloud Watching Day'.",
    "New pet trend: micro pigs become popular companions.",
    "Area woman makes headlines for creating a life-size gingerbread house.",
    "Local bakery introduces 'Cat-shaped Cupcakes' for charity.",
    "World's largest collection of rubber stamps found in attic.",
    "New discovery: plants that can sing when watered.",
    "Local gym introduces 'Dancing While Exercising' classes.",
    "Unbelievable: man claims he can teach fish to ride bicycles.",
    "City holds 'World's Largest Blanket Fort' competition.",
    "Residents start petition to create a holiday for cats.",
    "Local artist paints portraits of pets in funny costumes.",
    "New study reveals that laughter can increase lifespan.",
    "Area children host a 'Candlelight Storytelling Night'.",
    "Festival celebrates the art of paper airplanes.",
    "Community builds a giant sandcastle on the beach.",
    "Local librarian introduces 'Read to a Cat' program.",
    "Incredible story: squirrel saves baby bird from a cat.",
    "New fitness craze: 'Underwater Dance Party'.",
    "Residents hold annual 'Funny Face Contest'.",
    "Local chef creates a 'Pizza with Everything' menu.",
    "Festival dedicated to 'All Things Pickle' draws huge crowds.",
    "New study finds that playing with kittens reduces anxiety.",
    "Local man claims to have found a hidden treasure in his attic.",
    "Scientists discover new method for growing rainbow-colored flowers.",
    "Community hosts 'World's Largest S'mores' event.",
    "Area artist creates giant mural using only fruit.",
    "New pet trend: adopting miniature goats as companions.",
    "Local bakery offers free cookies to anyone who can make them laugh.",
    "Unbelievable: man claims to have trained his cat to fetch.",
    "Town holds annual 'Sandcastle Building Championship'.",
    "Incredible breakthrough: scientists find a way to 3D print food.",
    "Festival celebrates the art of origami with a folding contest.",
    "Local library offers 'Storytime for Dogs' event.",
    "New invention: self-replenishing fish tank.",
    "Area school introduces 'Gardening for Kids' program.",
    "World's first cat fashion show held in local park.",
    "Local woman discovers a way to turn trash into art.",
    "Community garden project helps neighbors connect.",
    "Incredible discovery: ants that can carry more than their weight.",
    "Local coffee shop introduces 'Dog-Friendly Treats' menu.",
    "Festival celebrates 'All Things Doughnut' with a tasting event.",
    "Area athlete sets new world record for fastest time to run in flip-flops.",
    "New study finds that listening to classical music can boost IQ.",
    "Local children start a 'Kindness Rocks' project.",
    "City council votes to build a 'Bicycle Highway' for eco-friendly transport.",
    "Unbelievable: man claims to have seen a unicorn in the wild.",
    "Local artist creates sculptures using only recycled materials.",
    "New trend: hosting 'Board Game Nights' in libraries.",
    "Festival dedicated to 'All Things Avocado' attracts food lovers.",
    "Incredible invention: smart fridge that suggests recipes.",
    "Residents hold 'World's Largest Group Hug' event.",
    "Local bakery creates cookie inspired by famous movie.",
    "Community comes together for annual 'Potluck Picnic'.",
    "Local farmer grows giant carrots that weigh over 10 pounds.",
    "New study reveals that petting dogs can lower blood pressure.",
    "Festival celebrates the beauty of rainbows with a parade.",
    "Area woman becomes local hero after rescuing kittens from a storm drain.",
    "Scientists develop new way to make ice cream healthier.",
    "Town holds 'World's Largest Scavenger Hunt' for charity.",
    "Local artist paints murals depicting local wildlife.",
    "New fitness class teaches participants how to dance like animals.",
    "Incredible breakthrough: scientists find a way to recycle ocean plastic.",
    "Festival celebrates 'All Things Pumpkin' with pie-eating contest.",
    "Residents start petition to build a 'Cat Sanctuary' in the park.",
    "Local musician composes symphony inspired by nature sounds.",
    "World record set for most rubber bands on a watermelon.",
    "Community garden project promotes sustainability and healthy eating.",
    "Local bakery offers free cookies to children under five.",
    "Unbelievable: man claims to have trained a raccoon to do tricks.",
    "New study finds that laughter yoga improves mental health.",
    "Festival dedicated to the art of kite flying brings joy to all.",
    "Local hero rescues lost puppy from a river.",
    "Scientists discover new species of butterfly in local park.",
    "Town hosts annual 'World's Largest Picnic' in the park.",
    "Local chef creates world's first vegan cheeseburger.",
    "New trend: hosting 'Mystery Dinner Parties' in homes.",
    "Festival celebrates 'All Things Marshmallow' with a roasting event.",
    "Incredible story: child finds rare coin while playing in the backyard.",
    "Local band gains popularity for playing only songs about vegetables.",
    "Community holds annual 'Storytelling Festival' with local authors.",
    "World's largest collection of snow globes discovered in basement.",
    "New study shows that being in nature can improve mood.",
    "Local artist creates portraits using only fruit and vegetables.",
    "Festival celebrates the joy of cooking with a bake-off.",
    "Residents start 'Good Deed Week' to spread kindness.",
    "Local bakery introduces 'Cookie Decorating Classes' for kids.",
    "Unbelievable: man claims to have invented a time machine made of pizza.",
    "Town holds annual 'Ice Cream Social' with local flavors.",
    "Local school implements 'No Homework Week' for students.",
    "Incredible invention: portable plant waterer for busy gardeners.",
    "Festival dedicated to 'All Things Cactus' attracts plant lovers.",
    "New study finds that doodling can boost creativity.",
    "Area children host a 'Rock Concert' in their backyard.",
    "City council votes to create a 'Pet Parade' for locals.",
    "Local author writes book about her cat's adventures.",
    "Community garden yields record number of giant pumpkins.",
    "World record set for most people wearing pajamas in public.",
    "Residents hold annual 'Hula Hoop Contest' for charity.",
    "Incredible story: dog saves family from a house fire.",
    "New app helps users find the best ice cream shops in town.",
    "Festival celebrates the art of bubble blowing with competitions.",
    "Local artist creates sculptures using only recycled glass.",
    "Area school introduces 'Mindfulness for Kids' program.",
    "World's largest rubber band ball discovered in local gym.",
    "Residents unite to plant trees in honor of Earth Day.",
    "Local chef wins award for best chocolate cake recipe.",
    "New trend: hosting 'Pet Costume Contests' in parks.",
    "Incredible invention: self-cleaning litter box for cats.",
    "Community comes together for 'Neighborhood Cleanup Day'.",
    "Local bakery offers free cupcakes on customers' birthdays.",
    "Unbelievable: man claims to have found a way to teleport.",
    "Town hosts annual 'World's Largest Chili Cook-off'.",
    "New study reveals that watching comedies improves relationships.",
    "Local artist creates interactive mural that changes with the weather.",
    "Festival celebrates 'All Things Gummy' with candy tastings.",
    "Residents hold annual 'Obstacle Course Race' for fun.",
    "Local hero saves baby bird from a cat's clutches.",
    "Scientists create biodegradable glitter to reduce plastic waste.",
    "Area school hosts 'Crazy Hair Day' to promote creativity.",
    "New pet trend: adopting rescue animals from shelters.",
    "Festival dedicated to 'All Things Cookie' attracts foodies.",
    "Incredible breakthrough: scientists find a way to grow fruit without seeds.",
    "Local musician performs 'Songs for Dogs' concert series.",
    "World's first cat yoga class held at local studio.",
    "Community garden project encourages sustainable practices.",
    "Local man breaks world record for longest time balancing on one foot.",
    "Residents unite for 'Good Neighbor Day' to spread kindness.",
    "Local bakery introduces 'Bacon-Flavored Cupcakes'.",
    "Unbelievable: man claims to have trained his fish to jump through hoops.",
    "Town holds annual 'Pancake Breakfast' for charity.",
    "New study shows that spending time with pets can reduce stress.",
    "Festival celebrates 'All Things Berry' with fruit picking.",
    "Local artist creates art installations from recycled toys.",
    "Incredible invention: hands-free dog leash for walkers.",
    "Community comes together for annual 'Community Potluck'.",
    "Local library offers 'Crafts for Cats' event.",
    "New pet trend: adopting hedgehogs as pets.",
    "Festival dedicated to 'All Things Popcorn' attracts snack lovers.",
    "Incredible story: family adopts a pig who becomes a beloved pet.",
    "Local chef creates a new dessert that changes flavors with every bite.",
    "New app helps users locate the nearest public restrooms.",
    "World's largest collection of model trains found in basement.",
    "Community organizes 'Outdoor Movie Night' in the park.",
    "Local artist creates paintings using only coffee.",
    "New study reveals that playing with puppies boosts happiness.",
    "Festival celebrates 'All Things Citrus' with fruit tastings.",
    "Residents hold annual 'Cookie Bake-off' for charity.",
    "Incredible discovery: new species of fish that can walk on land.",
    "Local musician composes music inspired by the sound of rain.",
    "New trend: hosting 'Potluck Dinners' to promote community bonding.",
    "Town holds 'World's Largest Lemonade Stand' for charity.",
    "Local man claims to have invented a machine that makes clouds.",
    "Scientists discover a way to grow strawberries that taste like chocolate.",
    "Festival celebrates the joy of reading with author signings.",
    "Community comes together to build a playground for kids.",
    "New pet trend: adopting older pets from shelters.",
    "Festival dedicated to 'All Things Jelly' attracts sweet lovers.",
    "Incredible breakthrough: scientists create a sustainable energy source from sunlight.",
    "Local bakery offers free pastries to first-time customers.",
    "Unbelievable: man claims to have found a portal to another dimension.",
    "Local author writes best-selling book about the history of ice cream.",
    "World record set for most people wearing silly socks in public.",
    "Residents hold annual 'Kite Festival' in the park.",
    "Local artist creates giant mosaic from bottle caps.",
    "New study shows that kindness can be contagious.",
    "Town hosts annual 'World's Largest Fruit Salad' competition.",
    "Festival celebrates the beauty of flowers with a parade.",
    "Local woman discovers a way to make paper from recycled jeans.",
    "Scientists find a new species of glowing mushroom.",
    "Incredible story: child creates a magical garden in their backyard.",
    "New trend: hosting 'Game Nights' to connect with neighbors.",
    "Community garden project promotes healthy eating habits.",
    "Local hero rescues stranded cat from a rooftop.",
    "Festival dedicated to 'All Things Honey' attracts food lovers.",
    "Area musician gains fame for performing with unusual instruments.",
    "New study reveals that pets can help improve mental health.",
    "Local bakery introduces a new line of gluten-free desserts.",
    "Unbelievable: man claims to have seen a mermaid in the ocean.",
    "Town holds 'World's Largest Snowman Building Contest'.",
    "Festival celebrates 'All Things Tea' with tastings.",
];

document.getElementById('generateNews').addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * news.length);
    document.getElementById('news').textContent = news[randomIndex];
});