document.getElementById('boredButton').addEventListener('click', function() {
    const messages = [
        "You're staring at the wall.",
        "You wonder how many times you can blink.",
        "You think about your life choices.",
        "You're now watching paint dry.",
        "You count the cracks in the wall.",
        "You replay old conversations in your mind.",
        "You question every decision you've ever made.",
        "You imagine what could have been.",
        "You contemplate your next meal.",
        "You feel the weight of your own thoughts.",
        "You think about the last time you felt truly happy.",
        "You listen to the faint sounds of the outside world.",
        "You think about calling a friend.",
        "You realize how long it’s been since you last laughed.",
        "You wonder if anyone else is thinking about you right now.",
        "You feel an itch on your arm that you can’t quite reach.",
        "You contemplate the meaning of life in its simplest form.",
        "You think about the laundry that needs folding.",
        "You notice the dust settling on your bookshelf.",
        "You start to create a mental list of things to do.",
        "You feel an overwhelming sense of nostalgia.",
        "You wonder if you’ll ever escape this monotony.",
        "You gaze at the ceiling, counting the tiles.",
        "You ponder your favorite childhood memory.",
        "You feel a twinge of regret for unfulfilled dreams.",
        "You wonder what your future self would think of you.",
        "You imagine the life you wanted at this moment.",
        "You think about the last book you read.",
        "You wonder how long it’s been since you went for a walk.",
        "You consider starting a journal to capture your thoughts.",
        "You feel the urge to scream into the void.",
        "You recall the taste of your favorite ice cream.",
        "You think about the friends you haven’t seen in years.",
        "You imagine how different your life could have been.",
        "You think about the last time you saw the stars.",
        "You remember a song that makes you smile.",
        "You wonder if you’ll ever find true love.",
        "You think about the dreams you had as a child.",
        "You hear the distant sound of laughter.",
        "You question the path you’ve chosen.",
        "You think about the people who have hurt you.",
        "You remember a compliment someone gave you.",
        "You feel the urge to paint or create something.",
        "You consider taking a trip somewhere new.",
        "You remember a time when you felt free.",
        "You wonder about the meaning behind your favorite song.",
        "You think about how much you’ve changed over the years.",
        "You ponder the relationships that matter most to you.",
        "You feel a wave of loneliness wash over you.",
        "You wonder if you’ll ever make a difference.",
        "You think about the hobbies you used to enjoy.",
        "You hear the ticking of the clock, marking each second.",
        "You imagine what life would be like without technology.",
        "You think about how many times you've said 'I'm fine' when you weren't.",
        "You remember your first crush and how it felt.",
        "You wonder if your pet is happy.",
        "You contemplate what it means to truly be yourself.",
        "You feel a sense of urgency to do something meaningful.",
        "You question the expectations others have of you.",
        "You think about how to make today better than yesterday.",
        "You imagine writing a letter to your younger self.",
        "You think about what brings you joy.",
        "You remember the last time you felt inspired.",
        "You wonder what it would be like to travel the world.",
        "You feel the warmth of the sun through the window.",
        "You question what happiness truly means to you.",
        "You think about the goals you set at the beginning of the year.",
        "You remember a lesson learned from a difficult experience.",
        "You wonder if you’re living up to your potential.",
        "You think about the things that make you anxious.",
        "You feel the urge to pick up a hobby again.",
        "You consider the impact of social media on your life.",
        "You imagine how your life will look in five years.",
        "You think about the last movie that made you cry.",
        "You remember a promise you made to yourself.",
        "You wonder if you’re on the right path.",
        "You feel a desire to reach out to someone you miss.",
        "You think about the beauty of nature and its simplicity.",
        "You question whether you’ve been kind enough to others.",
        "You remember a time when you felt invincible.",
        "You wonder about the stories behind the people you pass by.",
        "You think about the legacy you want to leave behind.",
        "You contemplate what success means to you.",
        "You remember the thrill of trying something new.",
        "You wonder if you should take a leap of faith.",
        "You feel a connection to the world around you.",
        "You think about the kindness of strangers.",
        "You question the choices you made in the heat of the moment.",
        "You imagine the sound of rain on a tin roof.",
        "You think about the comfort of a warm blanket.",
        "You feel the pull of a dream that feels just out of reach.",
        "You wonder if you should pursue a new career path.",
        "You think about what you would do if you won the lottery.",
        "You remember a funny moment that still makes you laugh.",
        "You contemplate the value of time spent alone.",
        "You feel the urge to write down your thoughts.",
        "You wonder if there’s a better way to live.",
        "You think about how far you’ve come.",
        "You remember the lessons learned from past mistakes.",
        "You wonder about the people you’ve lost touch with.",
        "You think about how to cherish the present moment."
    ];
    const randomMessage = messages[Math.floor(Math.random() * messages.length)];
    document.getElementById('status').textContent = randomMessage;
});
