const reasons = [
    "The page you are looking for is just too cool to exist.",
    "This page has gone on vacation.",
    "Error 404: Too many buttons, not enough time.",
    "You might find what you seek in the next dimension.",
    "The file has vanished into the void.",
    "Oops, it seems the page is playing hide and seek.",
    "404: Your search ended up in a black hole.",
    "This page is currently undergoing renovations.",
    "The page took a wrong turn at Albuquerque.",
    "We've misplaced it somewhere in the digital ether.",
    "The internet has misplaced this page.",
    "The page you're looking for has been abducted by aliens.",
    "404: The page is in a parallel universe now.",
    "Looks like the page is on strike today.",
    "We lost this page in the digital jungle.",
    "The page has flown the coop.",
    "404: This page took a one-way trip to nowhere.",
    "The file has gone into hiding.",
    "This page decided to go for a walk.",
    "404: The page you are looking for is in another castle.",
    "This link is just a ghost story now.",
    "We went looking for the page and found nothing.",
    "The page is out of stock.",
    "This page took a leap into the unknown.",
    "We can't seem to locate this page, sorry!",
    "404: The page went to a party and forgot to come back.",
    "The file you're looking for is lost in the cloud.",
    "404: Error in the space-time continuum.",
    "The page is currently being rebooted.",
    "We've sent out a search party for this page.",
    "404: This page is currently in a digital black hole.",
    "This page is lost in cyberspace, somewhere.",
    "The link you clicked is a phantom.",
    "404: The page was last seen sailing through the interwebs.",
    "This page is just a figment of your imagination.",
    "We can't seem to find this page at the moment.",
    "The page is out on a coffee break.",
    "404: The page is stuck in a loading screen.",
    "The page you're looking for is out of office.",
    "This page is in hiding until further notice.",
    "404: The page you're looking for has made an escape.",
    "This page is waiting for a better Wi-Fi connection.",
    "404: We lost this page in a sea of links.",
    "Looks like this page has left the building.",
    "The page has fallen into the abyss.",
    "404: Page not found, maybe try again later.",
    "The page took a detour to the wrong website.",
    "404: The page went off the grid.",
    "The page is currently buffering in another dimension.",
    "Oops, we lost track of this page.",
    "404: The page was last seen in the pixelated wilderness.",
    "This page has disappeared into thin air.",
    "The link you followed has taken a vacation.",
    "404: Error 404, page not found, maybe it’s still loading.",
    "This page has taken a detour into oblivion.",
    "404: The page just decided to vanish.",
    "The page is out of bounds.",
    "404: This page went on a one-way trip.",
    "This page is currently in digital limbo.",
    "404: This page took a wrong turn at the server.",
    "The file has gone on an intergalactic journey.",
    "404: This page is a unicorn — it doesn't exist.",
    "The page has left the chat.",
    "404: Your page request is lost in translation.",
    "This page is currently on a secret mission.",
    "404: This page is on a holiday from the internet.",
    "The page has gone underground.",
    "404: The page has been archived for eternity.",
    "We’ve sent a search party for this page, but no luck.",
    "The page has fallen through the cracks of the web.",
    "404: Error 404 – page not found in this realm.",
    "This page has disappeared without a trace.",
    "The page is currently out of reach.",
    "404: The page took a timeout.",
    "This page is under construction. Please come back later.",
    "404: The page has joined the digital afterlife."
];

document.getElementById('simulateError').addEventListener('click', function() {
    const randomIndex = Math.floor(Math.random() * reasons.length);
    document.getElementById('errorMessage').textContent = reasons[randomIndex];
});
