// Array of unmotivational phrases
const phrases = [
    "If at first, you don’t succeed, maybe you should just give up.",
    "You miss 100% of the naps you don’t take.",
    "Dream big... then go back to sleep.",
    "Procrastinate now, don’t put it off.",
    "Success is just failure that tried again.",
    "Why try when you can fail?",
    "Don't worry, the world is full of opportunities to not take advantage of.",
    "If you think about it, failure is just success in reverse.",
    "There's no point in making an effort; it usually leads to disappointment.",
    "Why climb the mountain when you can stay on the couch?",
    "The best way to predict your future is to not even try.",
    "If you can’t convince them, confuse them.",
    "Mistakes are proof you are trying... to fail spectacularly.",
    "Even a stopped clock is right twice a day, but that doesn't help much.",
    "Hard work often pays off after time, but laziness pays off now.",
    "The road to success is always under construction, so take a detour.",
    "Your only limit is your imagination... so stay in bed!",
    "Sometimes the best solution is to not try at all.",
    "Remember, you can’t fail if you don’t even start.",
    "If you think it’s hard, it probably is.",
    "You can't let the fear of striking out keep you from playing the game... because you probably will.",
    "If at first you don't succeed, redefine success.",
    "Overachieving is overrated.",
    "The best way to predict your future is to ignore it.",
    "You are unique, just like everyone else.",
    "Success is often just a fancy word for someone else's failure.",
    "When nothing goes right, go take a nap.",
    "Don't follow your dreams; follow your snacks.",
    "If it seems easy, you’re probably not doing it right.",
    "Dreaming is free; it’s waking up that costs you.",
    "Why make a plan when you can wing it and fail spectacularly?",
    "If you can dream it, you can probably mess it up.",
    "Every accomplishment starts with the decision to not try.",
    "Sometimes it’s better to let things be. Like your ambition.",
    "It’s always darkest before the dawn, but that’s when you should be sleeping.",
    "You can’t make everyone happy; you're not pizza.",
    "Don’t worry, you’ll always find a way to mess it up.",
    "If you're not part of the solution, there's money to be made in prolonging the problem.",
    "Remember, when in doubt, just do nothing.",
    "Just because you didn’t do it today doesn’t mean you can’t put it off until tomorrow.",
    "Work hard in silence; let your success be a thing of the past.",
    "It's okay to be a follower, especially of nap time.",
    "You’re never too old to set a new goal, especially one that involves no effort.",
    "In the game of life, you can either be a player or just watch from the sidelines.",
    "The harder you work, the more luck you seem to have... but that luck can be bad.",
    "Avoiding your responsibilities is a great way to lower stress.",
    "Being lazy is a skill, and I’m a master.",
    "They say money talks, but mine just waves goodbye.",
    "You can't teach an old dog new tricks, especially if the dog doesn't want to learn.",
    "Staying motivated is overrated; find joy in doing nothing instead.",
    "Sometimes it's best to just embrace mediocrity.",
    "Keep calm and carry on... until you realize you don’t want to.",
    "Dare to be different... just not too different.",
    "The only reason to chase your dreams is to wake up in the end.",
    "Life is short; don’t spend it doing things you don’t want to do.",
    "If you’re not failing, you’re just not trying hard enough to fail.",
    "It’s not about how hard you work; it’s about how little you can do and still get by.",
    "An attitude of hopelessness is still an attitude.",
    "Perseverance is just another word for not knowing when to quit.",
    "It's not whether you win or lose; it's how little effort you put in.",
    "Why put off until tomorrow what you can ignore today?",
    "Success is like a fart; it only matters to you.",
    "Don’t count your chickens before they hatch; just assume they won’t.",
    "All good things come to those who wait... and wait... and wait.",
    "The early bird might get the worm, but the second mouse gets the cheese.",
    "You don’t have to be great to start; you just have to be lazy.",
    "Optimism is just a way to look at failure with a smile.",
    "If you can’t dazzle them with brilliance, baffle them with laziness.",
    "Sitting on the couch is the perfect workout for my spirit.",
    "A goal without a plan is just a wish that you’ll probably forget about.",
    "Being average is the new exceptional.",
    "Be yourself; everyone else is already taken, and it's exhausting.",
    "Sometimes it’s just better to watch the world go by.",
    "The best things in life are free, including naps.",
    "Why not aim for mediocrity? It's much easier.",
    "Your future is bright... just as long as you keep your eyes closed.",
    "Dreams don’t work unless you do... which is why I don’t dream.",
    "Some people dream of success, while others wake up and work hard at avoiding it.",
    "If you have to think about it, you’re probably not interested enough.",
    "Being successful is overrated; being comfortable is where it’s at.",
    "If you can’t do it right, just don’t do it at all.",
    "Success is just failure that didn’t happen in public.",
    "The biggest risk is not taking one, especially if it involves effort.",
    "Ambition is great, but so is a well-deserved break.",
    "It’s not about how far you go; it’s about how little effort you put in.",
    "Embrace your inner sloth; they have it figured out.",
    "Make every day a lazy day.",
    "It's hard to soar with eagles when you're surrounded by turkeys.",
    "The greatest risk is doing nothing at all.",
    "You can’t please everyone, so just focus on doing nothing.",
    "Not every dream is worth chasing; some are meant to stay asleep.",
    "It's okay to be a mess sometimes; just don’t clean it up.",
    "Taking a break is sometimes the best thing you can do.",
    "There’s no problem that can’t be ignored until it goes away.",
    "Mediocrity: It’s a standard I can live up to.",
    "Failure is just another way of saying you’re not trying hard enough to succeed.",
    "The path to success is littered with people who didn't show up.",
    "If you don’t have a plan, you can’t make a mistake.",
    "You can't fail if you never try.",
    "Chasing your dreams is exhausting; enjoy a good nap instead.",
    "Sometimes, the best way to win is to not play the game.",
    "Life is like a box of chocolates; if you don’t like it, just put it down.",
    "If you can’t find a way, just lay down and wait.",
    "Good things come to those who wait, so just sit tight.",
    "Success comes to those who hustle; failure comes to those who relax.",
    "The secret to success is not trying at all.",
    "Avoiding work is a full-time job.",
    "The future is bright, just like the sleep you need.",
    "The best part of working hard is taking long breaks.",
    "Why be yourself when you can be a couch potato?",
    "Your biggest achievement today should be not doing anything.",
    "Nothing can hold you back like your own laziness.",
    "A lazy person is often more creative in finding ways to avoid work.",
    "The road less traveled is usually just a detour to a nap.",
    "Embrace the art of doing nothing; it’s a talent.",
    "Sometimes it's better to let others take the lead in not doing anything.",
    "Life’s a journey, but sometimes it’s okay to take a shortcut through your bed.",
    "If you can’t succeed, at least look good while failing.",
    "Your dreams are valid, but only if you feel like working towards them.",
    "Sometimes you just need to stop and smell the roses... and then ignore them.",
    "Life is a marathon, but it's okay to take a few breaks.",
    "An unmotivated mind is a beautiful thing.",
    "Don't worry about the future; it's easier that way.",
    "If your plans don’t work out, it’s probably for the best.",
    "Success is what happens when you don’t get in the way of yourself.",
    "The best part of waking up is going back to sleep.",
    "Never let your dreams be dreams; let them be distant memories.",
    "It’s easier to just not try at all.",
    "Find comfort in your lack of ambition.",
    "Be the reason someone gives up today.",
    "Resting is just as productive as working, if not more.",
    "If at first, you don’t succeed, redefine what success means to you.",
    "Don't stress the small stuff; it's all small stuff.",
    "The more you fail, the less you have to worry about succeeding.",
    "Always take the easy route; it’s less stressful.",
    "Success is for those who are willing to work hard... or just take long naps.",
    "Sometimes, the best action is no action at all.",
    "You don't need to be great to start; just avoid it altogether.",
    "Taking a break is not just important; it’s essential.",
    "The only guarantee in life is that nothing is guaranteed.",
    "You don’t have to succeed; you just have to not fail spectacularly.",
    "Sometimes it's better to let others do the hard work.",
    "Life is what happens when you’re too busy to make plans.",
    "You can’t win if you don’t play, but you can’t lose if you don’t try.",
    "Sometimes, just waking up is enough of an achievement.",
    "It’s okay to be lazy; just make it your lifestyle.",
    "Success can wait; take your time.",
    "If you aim low, you’ll never be disappointed.",
    "Don't worry about what could go wrong; just enjoy what is going wrong.",
    "Why take a leap of faith when you can sit back and watch others fall?",
    "Every day may not be good, but there’s something good in every nap.",
    "You can do anything, but that doesn’t mean you should.",
    "Inaction is a choice, and it’s a popular one.",
    "Why bother with effort when indifference is so much easier?",
    "Focus on your relaxation techniques; they’re far more important.",
    "Don’t stress yourself out trying to succeed; just chill.",
    "Let others worry about the future; you enjoy the present.",
    "When life gives you lemons, throw them back and demand chocolate.",
    "If nothing is going right, it’s time for a nap.",
    "You can't fail if you don't play the game.",
    "Sometimes it's best to just let life happen and watch it unfold.",
    "Hustle culture is overrated; embrace the art of chill.",
    "You can do anything, but not everything. So, choose nothing.",
    "Make today a lazy day; tomorrow can wait.",
    "If you feel overwhelmed, just don't do anything.",
    "Life is tough, but so are you. Just kidding; it's okay to take a break.",
    "Don’t just dream of success; dream of taking a long nap.",
    "The biggest motivation is knowing you can do nothing at all.",
    "If you can’t be the best, just be the laziest.",
    "When life gets tough, just get tougher... at doing nothing.",
    "Take pride in your ability to avoid stress.",
    "When in doubt, just sit down and think about how to not do anything.",
    "Life’s a picnic, so enjoy the food and forget the effort.",
    "You don’t need to make a mark on the world; just enjoy your spot on the couch.",
    "Success is subjective; so is laziness.",
    "The only thing standing between you and your dreams is your desire to actually achieve them.",
    "If at first you don’t succeed, then quit trying.",
    "Today’s forecast: 100% chance of napping.",
    "Why do it today when you can procrastinate indefinitely?",
    "Life is what you make of it; sometimes, it’s best to make nothing.",
    "Unmotivated? Perfect; that means you’re doing great!",
    "You’re doing amazing, sweetie; at being lazy.",
    "Your efforts are commendable, but so is your ability to do nothing.",
    "Not trying is the new trying.",
    "Why take the road less traveled when you can stay home?",
    "The best things in life are free... like naps.",
    "Let others chase their dreams; you enjoy yours from afar.",
    "You can have it all... but maybe not today.",
    "Success requires effort, and effort is overrated.",
    "Do what you love, but only if it involves little to no effort.",
    "Life is short; don’t waste it trying to make a mark.",
    "Finding joy in nothing is an art form.",
    "Lazy is the new black.",
    "If you don’t feel like working, it’s probably best to just take a break.",
    "Work smarter, not harder... or just don’t work at all.",
    "It’s not about the destination; it’s about the journey to the couch.",
    "Don't just follow your dreams; avoid them altogether.",
    "Sometimes doing nothing is the most productive thing you can do.",
    "You’ll never regret a nap.",
    "Embrace the chaos of your unmotivated life.",
    "Success is relative; so is laziness.",
    "Why strive for greatness when mediocrity is within reach?",
    "If you don’t want to do it, just don’t.",
    "Sometimes you just have to let go of everything and take a nap.",
    "Not every battle is worth fighting; sometimes, it’s best to retreat.",
    "You don’t need to prove yourself; just relax.",
    "In a world full of hustle, be the one who takes a break.",
    "Doing nothing can be a full-time job.",
    "Let go of your ambitions; they’re holding you back.",
    "Success is overrated; enjoy your free time.",
    "If it’s meant to be, it’ll happen... or it won’t, and that’s fine too.",
    "Take life one nap at a time.",
    "Why push yourself when you can pull yourself back?",
    "Your dream life is waiting... but so is your couch.",
    "Let’s not take life too seriously; it’s not like anyone gets out alive.",
    "You can’t always get what you want; especially if you’re not willing to work for it.",
    "Why work for your dreams when you can sleep through them?",
    "Remember, you don’t have to achieve anything; just exist.",
    "If you can’t achieve greatness, at least look good while avoiding it.",
    "If you don’t try, you can’t fail... which is the best outcome.",
    "The secret to life is simple: take it easy.",
    "It’s okay to be a dreamer, as long as you stay asleep.",
    "Find joy in doing nothing; it’s a lost art.",
    "Don’t worry about tomorrow; it can wait.",
    "Napping is just your body’s way of recharging for more laziness.",
    "If at first you don’t succeed, just quit.",
    "Motivation is just a myth; enjoy your procrastination.",
    "Life is what you make it... unless you don’t want to make it.",
    "Never underestimate the power of doing absolutely nothing.",
    "In the end, it’s not the years in your life that count; it’s the naps.",
    "The grass is always greener on the other side... until you realize you don’t care.",
    "It’s okay to take a backseat in life; let others drive.",
    "Don’t worry about being perfect; just be lazy.",
    "Chase your dreams... just make sure to stop for naps along the way.",
    "Don’t follow your heart; follow your couch.",
    "Remember, effort is optional.",
    "Life is too short to take seriously; just take naps instead.",
    "When life gets you down, just sleep it off.",
    "Dreams are for dreamers; stay asleep.",
    "In the grand scheme of things, who cares?",
    "Let others worry about success; you enjoy your leisure.",
    "Success is a journey, but so is taking a break.",
    "The only failure is not trying... and that’s perfectly fine.",
    "Sometimes you just need to sit back and let life happen.",
    "If it’s hard, it’s probably not worth doing.",
    "Don’t put pressure on yourself; just enjoy the ride.",
    "Why do today what you can put off until tomorrow?",
    "Be the reason someone stops trying today.",
    "When the going gets tough, the tough take a nap.",
    "You don’t need to conquer the world; just enjoy your space.",
    "Sometimes it’s best to just watch life unfold.",
    "Every day is a good day to do nothing.",
    "Why strive for success when you can just sit back?",
    "Life’s too short; avoid stress.",
    "You’ll get there eventually... or you won’t, and that’s okay.",
    "Don’t let anyone tell you you’re not doing enough; they don’t know you.",
    "Sometimes it’s good to just embrace the chaos.",
    "Success is subjective; so is laziness.",
    "Being productive is overrated.",
    "Sometimes, doing nothing is the best thing you can do.",
    "If you can’t find time to relax, make time.",
    "Don’t push yourself; enjoy the present moment.",
    "Take a step back and just breathe.",
    "Don’t worry about the little things; they don’t matter.",
    "It’s okay to just be; you don’t have to do anything.",
    "Life is too short for unnecessary effort.",
    "Chase your dreams, but don’t forget to take breaks.",
    "Sometimes it’s best to just let life be.",
    "If you can’t enjoy the journey, it’s time to take a break.",
    "Being lazy is an art form; perfect it.",
    "Embrace the unmotivated you; it’s perfectly fine.",
    "Life is full of possibilities; choose to do nothing.",
    "Sometimes the best choice is not to choose at all.",
    "Just because you can, doesn’t mean you should.",
    "Take time to relax; it’s more important than you think.",
    "You have all the time in the world to do nothing.",
    "Make laziness your priority.",
    "Life is a journey, and yours is on a leisurely pace.",
    "Success is for those who chase it; you prefer to stroll.",
    "Life is too unpredictable to stress over.",
    "Don’t let ambition cloud your desire to relax.",
    "You are enough, just as you are; lazy and all.",
    "Sometimes you just need to sit back and do nothing at all.",
    "Relaxation is the key to happiness.",
    "Why hustle when you can enjoy life’s little pleasures?",
    "In the grand scheme of things, it’s all about balance.",
    "Sometimes less is more; especially when it comes to effort.",
    "Embrace your inner couch potato.",
    "Every day is an opportunity to take a break.",
    "Dreams can wait; naps can’t.",
    "Take a moment to appreciate your ability to do nothing.",
    "Let’s not complicate life with unnecessary effort.",
    "Why work hard when you can work smart... or not at all?",
    "Sometimes it’s okay to just sit back and enjoy the view.",
    "The less you do, the less you have to worry about.",
    "Life is a journey; enjoy the ride, or don’t.",
    "Sometimes doing nothing is the best form of resistance.",
    "Why strive for success when you can just exist?",
    "Enjoy every moment of your lazy life.",
    "In the end, it’s the simple things that matter most.",
    "Sometimes the best thing to do is absolutely nothing.",
    "You don’t have to prove yourself; just relax.",
    "Life’s too short to overthink; just enjoy the moment.",
    "If you can’t find motivation, that’s okay; enjoy the lack of it.",
    "Relaxation is a skill; master it.",
    "Life is what you make of it; make it a break.",
    "Don’t let ambition ruin your day.",
    "Sometimes you just need to let go of everything and breathe.",
    "Life is full of challenges; choose to rise above by doing nothing.",
    "Success is overrated; embrace the art of relaxation.",
    "You have the power to do nothing; use it wisely.",
    "Don’t just survive; thrive in your laziness.",
    "Life is too short to chase after dreams; take a break instead.",
    "Sometimes it’s good to step back and just breathe.",
    "Why stress over success when you can chill?",
    "Find joy in doing nothing; it’s an underrated skill.",
    "Your worth is not determined by your productivity.",
    "Sometimes you just need to embrace the unmotivated you.",
    "Life is a journey, but sometimes it’s okay to stop and enjoy the view.",
    "It’s not about the effort; it’s about the enjoyment.",
    "Sometimes doing nothing is the best choice you can make.",
    "Chase your dreams when you’re ready; until then, enjoy your naps.",
    "Don’t worry about tomorrow; it will come whether you do anything or not.",
    "Sometimes the best action is no action at all.",
    "The world can wait while you take a nap.",
    "You can do anything... as long as you don’t have to do anything.",
    "Life is a series of choices; make the choice to do nothing.",
    "Sometimes less is more; especially when it comes to effort.",
    "The only thing you need to achieve is relaxation.",
    "Life is a journey, and yours is just beginning... or not.",
    "Sometimes the greatest accomplishment is doing nothing.",
    "When in doubt, take a nap.",
    "It’s not about the destination; it’s about the journey to relaxation.",
    "You’re doing great at being unmotivated; keep it up!",
    "Life is a series of naps; embrace them.",
    "Let others chase their dreams; you enjoy your rest.",
    "If you don’t feel like doing anything, that’s perfectly okay.",
    "You’re doing amazing; just remember to take it easy.",
    "The secret to life is simple: do nothing.",
    "Life is too short to take seriously; enjoy the ride.",
    "You don’t have to achieve anything today; just exist.",
    "Sometimes it’s good to just sit back and enjoy the moment.",
    "Success is subjective; so is laziness.",
    "Take a moment to appreciate the beauty of doing nothing.",
    "Why rush when you can relax?",
    "Sometimes it’s best to just let life unfold.",
    "The less you do, the less you have to worry about.",
    "You can have it all... tomorrow.",
    "Life is too unpredictable to stress over; take it easy.",
    "In the grand scheme of things, it’s all about balance.",
    "Don’t let ambition cloud your desire to relax.",
    "Sometimes you just need to embrace the chaos of life.",
    "Your worth is not determined by your productivity; relax.",
    "You can’t fail if you don’t try; so just don’t.",
    "Life is full of possibilities; choose to do nothing.",
    "Sometimes the best choice is not to choose at all.",
    "Just because you can, doesn’t mean you should.",
    "Take time to relax; it’s more important than you think.",
    "You have all the time in the world to do nothing.",
    "Make laziness your priority; it’s a noble cause.",
    "Life is a journey, and yours is on a leisurely pace.",
    "Success is for those who chase it; you prefer to stroll.",
    "Sometimes you just need to sit back and do nothing at all.",
    "Don’t worry about the little things; they don’t matter.",
    "It’s okay to just be; you don’t have to do anything.",
    "Life is too short for unnecessary effort.",
    "Chase your dreams, but don’t forget to take breaks.",
    "Sometimes it’s best to just let life be.",
    "If you can’t enjoy the journey, it’s time to take a break.",
    "Being lazy is an art form; perfect it.",
    "You don’t have to prove yourself; just relax.",
    "Life’s too short to overthink; just enjoy the moment.",
    "If you can’t find motivation, that’s okay; enjoy the lack of it.",
    "Relaxation is a skill; master it.",
    "Life is what you make of it; make it a break.",
    "Don’t let ambition ruin your day.",
    "Sometimes you just need to let go of everything and breathe.",
    "Life is full of challenges; choose to rise above by doing nothing.",
    "Success is overrated; embrace the art of relaxation.",
    "You have the power to do nothing; use it wisely.",
    "Don’t just survive; thrive in your laziness.",
    "Life is too short to chase after dreams; take a break instead.",
    "Sometimes it’s good to step back and just breathe.",
    "Why stress over success when you can chill?",
    "Find joy in doing nothing; it’s an underrated skill.",
    "Your worth is not determined by your productivity.",
    "Sometimes you just need to embrace the unmotivated you.",
    "Life is a journey, but sometimes it’s okay to stop and enjoy the view.",
    "It’s not about the effort; it’s about the enjoyment.",
    "Sometimes doing nothing is the best choice you can make.",
    "Chase your dreams when you’re ready; until then, enjoy your naps.",
    "Don’t worry about tomorrow; it will come whether you do anything or not.",
    "Sometimes the best action is no action at all.",
    "The world can wait while you take a nap.",
    "You can do anything... as long as you don’t have to do anything.",
    "Life is a series of choices; make the choice to do nothing.",
    "Sometimes less is more; especially when it comes to effort.",
    "The only thing you need to achieve is relaxation.",
    "Life is a journey, and yours is just beginning... or not.",
    "Sometimes the greatest accomplishment is doing nothing.",
    "When in doubt, take a nap.",
    "It’s not about the destination; it’s about the journey to relaxation.",
    "You’re doing great at being unmotivated; keep it up!",
    "Life is a series of naps; embrace them.",
    "Let others chase their dreams; you enjoy your rest.",
    "If you don’t feel like doing anything, that’s perfectly okay.",
    "You’re doing amazing; just remember to take it easy.",
    "The secret to life is simple: do nothing.",
    "Life is too short to take seriously; enjoy the ride.",
    "You don’t have to achieve anything today; just exist.",
    "Sometimes it’s good to just sit back and enjoy the moment.",
    "Success is subjective; so is laziness.",
    "Take a moment to appreciate the beauty of doing nothing.",
    "Why rush when you can relax?",
    "Sometimes it’s best to just let life unfold.",
    "The less you do, the less you have to worry about.",
    "You can have it all... tomorrow.",
    "Life is too unpredictable to stress over; take it easy.",
    "In the grand scheme of things, it’s all about balance.",
    "Don’t let ambition cloud your desire to relax.",
    "Sometimes you just need to embrace the chaos of life.",
    "Your worth is not determined by your productivity; relax.",
    "You can’t fail if you don’t try; so just don’t."
];

document.getElementById('generatePoster').addEventListener('click', function() {
    const randomIndex = Math.floor(Math.random() * phrases.length);
    document.getElementById('unmotivationalText').textContent = phrases[randomIndex];
});
